apiVersion: v1
kind: Pod
metadata:
  name: {{ include "my-app-workflow.fullname" . }}
  labels:
    {{- include "my-app-workflow.selectorLabels" . | nindent 4 }}
spec:
  containers:
  - name: my-app
    image: my-app:{{ .Values.app.tag }}
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
        name: http-web-svc
    {{ if eq .Values.app.tag "dev" }}
    volumeMounts:
      - name: {{ include "my-app-workflow.fullname" . }}-src
        mountPath: app/app
    {{ end }}
    env:
      - name: WATCHPACK_POLLING
        value: "true"
  {{ if eq .Values.app.tag "dev" }}
  volumes:
    - name: {{ include "my-app-workflow.fullname" . }}-src
      persistentVolumeClaim:
        claimName: {{ include "my-app-workflow.fullname" . }}
  {{ end }}

