apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-app-workflow.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: {{ include "my-app-workflow.fullname" . }}-src
  resources:
    requests:
      storage: {{ .Values.sourceCode.storage }}
