apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-app-workflow.fullname" . }}-src
  labels:
    {{- include "my-app-workflow.selectorLabels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.sourceCode.storage }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: {{ .Values.sourceCode.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
