apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
spec:
  containers:
  - name: my-app
    image: my-app:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
        name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app.kubernetes.io/name: my-app
  type: LoadBalancer
  ports:
  - name: my-app-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
